package:
  name: pysim
  version: "1.0.0"

source:
  path: ..

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - pysim

about:
  home: https://github.com/KyunghanMin/StateBasedPredictionAndControl
